SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (1, N'Kayak', N'A boat for one person                                                                               ', N'Watersports', CAST(275.05 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (2, N'Lifejacket', N'Protective and fashionable                                                                          ', N'Watersports', CAST(48.95 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (3, N'Soccer Ball', N'FIFA approved size and weight                                                                       ', N'Soccer', CAST(19.50 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (4, N'Corner Flags', N'Give your playing field a professional touch                                                        ', N'Soccer', CAST(34.95 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (5, N'Stadium', N'Flat-packed, 35 000-seat stadium                                                                    ', N'Soccer', CAST(79500.00 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (6, N'Thinking cap', N'Improve your brain efficiecy                                                                        ', N'Chess', CAST(16.00 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (7, N'Unsteady chair', N'Secretly give your opponent a disadvantage                                                          ', N'Chess', CAST(29.95 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (8, N'Human Chess Board', N'A fun game for the family                                                                           ', N'Chess', CAST(75.00 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductId], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (9, N'Bling-Bling King', N'Gold-plated, diamond-studded King                                                                   ', N'Chess', CAST(1200.00 AS Decimal(16, 2)), <SQLVARIANT>, NULL)
SET IDENTITY_INSERT [dbo].[Products] OFF
